# Generated by Django 2.2.28 on 2023-09-11 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.URLField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=100, null=True)),
                ('url', models.URLField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Stire',
        ),
    ]
